# Generated by Django 4.1.1 on 2025-09-27 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad_complementaria_comedor', '0001_initial'),
        ('asistentes_diarios_comedor', '0001_initial'),
        ('localidad', '0001_initial'),
        ('cantidad_trabajadores_comedor', '0001_initial'),
        ('provincia', '0001_initial'),
        ('fuente_agua_comedor', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('gobierno_local', '0001_initial'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('barrio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio')),
                ('calle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número')),
                ('entre_calles', models.CharField(blank=True, max_length=200, null=True, verbose_name='Entre Calles')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True, verbose_name='Longitud')),
                ('ubicacion_georreferencial', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=9, null=True, verbose_name='Ubicacion GEO')),
                ('fecha_inicio_actividad', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de actividad')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fuente_agua_potable', models.BooleanField(blank=True, default=False, null=True, verbose_name='Fuente de Agua Potable')),
                ('actividades', models.ManyToManyField(blank=True, to='actividad_complementaria_comedor.actividadcomplementariacomedor')),
                ('asistentes_diarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistentes_diarios_comedor.asistentesdiarioscomedor')),
                ('cantidad_trabajadores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantidad_trabajadores_comedor.cantidadtrabajadorescomedor')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('fuente_agua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuente_agua_comedor.fuenteaguacomedor')),
                ('gobierno_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gobierno_local.gobiernolocal')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localidad.localidad')),
                ('organizacion_regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.organizacion')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provincia.provincia')),
            ],
            options={
                'verbose_name_plural': 'Comedores',
            },
        ),
        migrations.CreateModel(
            name='FuncionamientoComedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=9)),
                ('funcionamiento', models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=30)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
            ],
            options={
                'verbose_name_plural': 'Funcionamiento de Comedores',
            },
        ),
    ]
