# Generated by Django 4.1.1 on 2025-09-27 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo_energia_comedor', '0001_initial'),
        ('comedor', '0001_initial'),
        ('servicio_comedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedor',
            name='responsable_comedor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Responsable Comedor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comedor',
            name='servicio_comedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio_comedor.serviciocomedor'),
        ),
        migrations.AddField(
            model_name='comedor',
            name='tipos_energia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_energia_comedor.tipoenergiacomedor'),
        ),
    ]
