# Generated by Django 4.1.1 on 2025-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_comedor', '0001_initial'),
        ('comedor', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comedor',
            name='servicio_comedor',
        ),
        migrations.AddField(
            model_name='comedor',
            name='servicio_comedor',
            field=models.ManyToManyField(blank=True, to='servicio_comedor.serviciocomedor'),
        ),
    ]
