# Generated by Django 4.1.1 on 2025-09-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='images')),
                ('horario', models.CharField(choices=[('desayuno_merienda_bebidas', 'Desayuno/Merienda - Bebidas'), ('desayuno_merienda_comida', 'Desayuno/Merienda - Comida'), ('almuerzo_cena_entrada', 'Almuerzo/Cena - Entrada'), ('almuerzo_cena_plato_principal', 'Almuerzo/Cena - Plato Principal'), ('almuerzo_cena_postre', 'Almuerzo/Cena - Postre')], max_length=50, verbose_name='Horario a servir')),
                ('alimento', models.ManyToManyField(blank=True, to='alimento.alimento')),
            ],
            options={
                'verbose_name_plural': 'Comidas',
            },
        ),
    ]
