# Generated by Django 4.1.1 on 2025-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.RemoveField(
            model_name='comida',
            name='horario',
        ),
        migrations.AddField(
            model_name='comida',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='comida.horario', verbose_name='Horarios a servir'),
        ),
    ]
