# Generated by Django 4.1.1 on 2025-09-27 23:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0.001)])),
            ],
            options={
                'verbose_name_plural': 'Alimentos de una encuesta',
            },
        ),
        migrations.CreateModel(
            name='NoSeSirvioEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('funcionamiento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=30)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
            ],
            options={
                'verbose_name_plural': 'Encuestas que no se sirvieron',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de inicio de actividad')),
                ('cantidad_rango_1', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Rango 1')),
                ('cantidad_rango_2', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Rango 2')),
                ('cantidad_rango_3', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Rango 3')),
                ('cantidad_rango_4', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Rango 4')),
                ('funcionamiento', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=30)),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.organizacion')),
            ],
            options={
                'verbose_name_plural': 'Encuestas',
            },
        ),
    ]
