# Generated by Django 4.1.1 on 2025-09-27 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comida', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encuesta', '0001_initial'),
        ('alimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='responsable_comedor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Responsable Comedor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alimentoencuesta',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimento.alimento'),
        ),
        migrations.AddField(
            model_name='alimentoencuesta',
            name='comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida'),
        ),
        migrations.AddField(
            model_name='alimentoencuesta',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta'),
        ),
        migrations.AddField(
            model_name='alimentoencuesta',
            name='unidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='alimento.unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='nosesirvioencuesta',
            unique_together={('fecha', 'comedor', 'funcionamiento')},
        ),
    ]
