# Generated by Django 4.1.1 on 2025-10-02 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentoencuesta',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
