# Generated by Django 4.1.1 on 2025-10-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_fix_cantidad_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentoencuesta',
            name='momento_dia',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], default='almuerzo', max_length=30, verbose_name='Momento del día'),
        ),
    ]
