# Generated by Django 4.1.1 on 2025-10-06 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_fix_cantidad_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='cantidad_rango_5',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de Comensales - Adultos Mayores (+60 años)'),
        ),
    ]
