# Generated by Django 4.1.1 on 2025-10-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0004_alimentoencuesta_momento_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentoencuesta',
            name='momento_dia',
        ),
        migrations.AddField(
            model_name='alimentoencuesta',
            name='etapa_comida',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('plato_principal', 'Plato Principal'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('acompañamiento', 'Acompañamiento')], default='plato_principal', max_length=30, verbose_name='Etapa de la comida'),
        ),
    ]
