# Generated by Django 4.1.1 on 2025-09-27 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('logo', models.ImageField(upload_to='images')),
                ('estado', models.BooleanField(default=False, verbose_name='Activo')),
                ('es_organizacion_regional', models.BooleanField(default=False, verbose_name='Es regional')),
                ('organizacion_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacion.organizacion')),
                ('tipo_organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_organizacion.tipoorganizacion')),
            ],
            options={
                'verbose_name_plural': 'Organizaciones',
            },
        ),
    ]
