# Generated by Django 4.1.1 on 2025-09-27 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuesta', '0001_initial'),
        ('organizacion', '0001_initial'),
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportesGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Reportes generales',
            },
        ),
        migrations.CreateModel(
            name='ReportesRaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Reportes de raciones',
            },
        ),
        migrations.CreateModel(
            name='ReporteNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('porciones', models.FloatField()),
                ('hidratos', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasasSaturadas', models.FloatField()),
                ('grasasTotales', models.FloatField()),
                ('kilocalorias', models.FloatField()),
                ('sodio', models.FloatField()),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.comedor')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.encuesta')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.organizacion')),
            ],
            options={
                'verbose_name_plural': 'Reportes Nutricional',
            },
        ),
    ]
