# Generated by Django 4.1.1 on 2025-10-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportesNutricionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Reportes nutricionales',
            },
        ),
    ]
