# Generated by Django 4.1.1 on 2025-10-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_add_reportes_nutricionales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportesnutricionales',
            options={'verbose_name': 'Reporte nutricional', 'verbose_name_plural': 'Reportes nutricionales'},
        ),
    ]
