# Generated by Django 4.1.1 on 2025-10-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0003_update_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportesnutricionales',
            options={'verbose_name': 'Reportes nutricionales', 'verbose_name_plural': 'Reportes nutricionales'},
        ),
    ]
