# Generated by Django 4.1.1 on 2025-09-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlimentoSARA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('cantidad_porcion', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('hidratos_carbono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('proteinas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grasas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grasas_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('energia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sodio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='images')),
                ('cantidad_porcion', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Cantidad de Referencia')),
                ('hidratos_carbono', models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Hidratos de Carbono')),
                ('proteinas', models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Proteinas')),
                ('grasas', models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Grasas Saturadas')),
                ('grasas_totales', models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Grasas Totales')),
                ('energia', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Kilocalorias')),
                ('sodio', models.DecimalField(decimal_places=2, help_text='En gramos', max_digits=16, verbose_name='Sodio')),
                ('unidades', models.ManyToManyField(to='alimento.unidad', verbose_name='Unidades utilizables')),
            ],
            options={
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
