# Generated by Django 4.1.1 on 2025-09-28 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentosara',
            options={'ordering': ['nombre'], 'verbose_name': 'Alimento SARA', 'verbose_name_plural': 'Alimentos SARA'},
        ),
    ]
