# Generated by Django 4.1.1 on 2025-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0002_alter_alimentosara_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='equivalencia_gramos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Equivalencia de 1 unidad en gramos', max_digits=16, null=True, verbose_name='Equivalencia en gramos'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='equivalencia_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Equivalencia de 1 unidad en ml', max_digits=16, null=True, verbose_name='Equivalencia en ml'),
        ),
    ]
