# Generated by Django 4.1.1 on 2025-10-15 03:45

from django.db import migrations


def clear_alimento_sara(apps, schema_editor):
    """
    Limpia todos los datos de la tabla AlimentoSARA
    """
    AlimentoSARA = apps.get_model('alimento', 'AlimentoSARA')
    # Eliminar todos los registros de AlimentoSARA
    deleted_count = AlimentoSARA.objects.all().count()
    AlimentoSARA.objects.all().delete()
    print(f"Se eliminaron {deleted_count} registros de AlimentoSARA")


def reverse_clear_alimento_sara(apps, schema_editor):
    """
    Función reversa - no hace nada ya que no podemos recuperar los datos eliminados
    """
    print("Migración revertida - los datos de AlimentoSARA no se pueden recuperar automáticamente")


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0004_auto_20251014_2302'),
    ]

    operations = [
        migrations.RunPython(clear_alimento_sara, reverse_clear_alimento_sara),
    ]
