# Generated by Django 4.1.1 on 2025-10-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0004_alimento_acidos_grasos_monoinsaturados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentosara',
            name='acidos_grasos_monoinsaturados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Ácidos Grasos Monoinsaturados'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='acidos_grasos_poliinsaturados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Ácidos Grasos Poliinsaturados'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='acidos_grasos_saturados',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Ácidos Grasos Saturados'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='agua',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Agua'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='calcio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Calcio'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='cenizas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Cenizas'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='colesterol',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Colesterol'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='fibra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Fibra'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='folatos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En μg', max_digits=10, verbose_name='Folatos'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='fosforo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Fósforo'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='hierro',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Hierro'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='lipidos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Lípidos'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='niacina',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Niacina'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='potasio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Potasio'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='riboflavina',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Riboflavina (B2)'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='tiamina',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Tiamina (B1)'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='vitamina_a',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En μg RAE', max_digits=10, verbose_name='Vitamina A'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='vitamina_b12',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En μg', max_digits=10, verbose_name='Vitamina B12'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='vitamina_c',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Vitamina C'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='vitamina_d',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En UI', max_digits=10, verbose_name='Vitamina D'),
        ),
        migrations.AddField(
            model_name='alimentosara',
            name='zinc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Zinc'),
        ),
        migrations.AlterField(
            model_name='alimentosara',
            name='energia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En kcal', max_digits=10, verbose_name='Energía'),
        ),
        migrations.AlterField(
            model_name='alimentosara',
            name='grasas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos - usar acidos_grasos_saturados', max_digits=10, null=True, verbose_name='Grasas Saturadas (Legacy)'),
        ),
        migrations.AlterField(
            model_name='alimentosara',
            name='grasas_totales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos - usar lipidos', max_digits=10, null=True, verbose_name='Grasas Totales (Legacy)'),
        ),
        migrations.AlterField(
            model_name='alimentosara',
            name='hidratos_carbono',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Hidratos de Carbono'),
        ),
        migrations.AlterField(
            model_name='alimentosara',
            name='proteinas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=10, verbose_name='Proteínas'),
        ),
        migrations.AlterField(
            model_name='alimentosara',
            name='sodio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En mg', max_digits=10, verbose_name='Sodio'),
        ),
    ]
