# Generated by Django 4.1.1 on 2025-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0005_auto_20251015_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='acido_folico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En μg', max_digits=16, null=True, verbose_name='Ácido Fólico'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='acidos_grasos_monoinsaturados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos', max_digits=16, null=True, verbose_name='Ácidos Grasos Monoinsaturados'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='acidos_grasos_poliinsaturados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos', max_digits=16, null=True, verbose_name='Ácidos Grasos Poliinsaturados'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='calcio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Calcio'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='colesterol',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Colesterol'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='fibra_dietetica',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos', max_digits=16, null=True, verbose_name='Fibra Dietética'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='fosforo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Fósforo'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='hierro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Hierro'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='magnesio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Magnesio'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='potasio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Potasio'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='vitamina_a',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En μg', max_digits=16, null=True, verbose_name='Vitamina A'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='vitamina_b1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Vitamina B1 (Tiamina)'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='vitamina_b2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Vitamina B2 (Riboflavina)'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='vitamina_b3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Vitamina B3 (Niacina)'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='vitamina_c',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Vitamina C'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='zinc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En mg', max_digits=16, null=True, verbose_name='Zinc'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='energia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Kilocalorias'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos', max_digits=16, null=True, verbose_name='Grasas Saturadas'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasas_totales',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos', max_digits=16, null=True, verbose_name='Grasas Totales'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='hidratos_carbono',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos', max_digits=16, null=True, verbose_name='Hidratos de Carbono'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos', max_digits=16, null=True, verbose_name='Proteinas'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='sodio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En gramos', max_digits=16, null=True, verbose_name='Sodio'),
        ),
    ]
