# Generated by Django 4.1.1 on 2025-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0006_alimento_acido_folico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='acido_folico',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='acidos_grasos_monoinsaturados',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='acidos_grasos_poliinsaturados',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='calcio',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='colesterol',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='fibra_dietetica',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='fosforo',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='hierro',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='magnesio',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='potasio',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='vitamina_a',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='vitamina_b1',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='vitamina_b2',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='vitamina_b3',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='vitamina_c',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='zinc',
        ),
        migrations.AlterField(
            model_name='alimento',
            name='energia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Kilocalorias'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=16, verbose_name='Grasas Saturadas'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='grasas_totales',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=16, verbose_name='Grasas Totales'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='hidratos_carbono',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=16, verbose_name='Hidratos de Carbono'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=16, verbose_name='Proteinas'),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='sodio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='En gramos', max_digits=16, verbose_name='Sodio'),
        ),
    ]
